#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Vsd_ContractType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("General Service Agreement", 6, "#0000ff")]
		GeneralServiceAgreement = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Memorandum of Understanding", 7, "#0000ff")]
		MemorandumOfUnderstanding = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Community Accountability Programs", 2, "#0000ff")]
		TuaCommunityAccountabilityPrograms = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Continuing Agreement", 1, "#0000ff")]
		TuaContinuingAgreement = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Crime Prevention", 3, "#0000ff")]
		TuaCrimePrevention = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Custom Services", 5, "#0000ff")]
		TuaCustomServices = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Provincial Association", 4, "#0000ff")]
		TuaProvincialAssociation = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TUA - Victim Services/VAWP", 0, "#0000ff")]
		TuaVictimServicesVawp = 100000000,
	}
}
#pragma warning restore CS1591
