global using Database;
global using Database.Model;
global using Manager;
global using Manager.Contract;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using Resources;
global using Shared.Contract;
global using Task = System.Threading.Tasks.Task;
