#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_RoutingRuleSetValidation")]
	public partial class @__RoutingRuleSetValidationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RoutingRuleSet = "RoutingRuleSet";
		}
		
		public const string ActionLogicalName = "_RoutingRuleSetValidation";
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSet
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSet"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSet"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSet"] = value;
			}
		}
		
		public @__RoutingRuleSetValidationRequest()
		{
			this.RequestName = "_RoutingRuleSetValidation";
			this.RoutingRuleSet = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_RoutingRuleSetValidation")]
	public partial class @__RoutingRuleSetValidationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ValidationMessageToDisplay = "ValidationMessageToDisplay";
			public const string ValidationMessageToDownload = "ValidationMessageToDownload";
		}
		
		public const string ActionLogicalName = "_RoutingRuleSetValidation";
		
		public @__RoutingRuleSetValidationResponse()
		{
		}
		
		public string ValidationMessageToDisplay
		{
			get
			{
				if (this.Results.Contains("ValidationMessageToDisplay"))
				{
					return ((string)(this.Results["ValidationMessageToDisplay"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ValidationMessageToDisplay"] = value;
			}
		}
		
		public string ValidationMessageToDownload
		{
			get
			{
				if (this.Results.Contains("ValidationMessageToDownload"))
				{
					return ((string)(this.Results["ValidationMessageToDownload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ValidationMessageToDownload"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
