#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_SaveServiceTreeData")]
	public partial class @__SaveServiceTreedAtaRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RootNodeId = "RootNodeId";
			public const string ResourceRuleList = "ResourceRuleList";
		}
		
		public const string ActionLogicalName = "_SaveServiceTreeData";
		
		public string RootNodeId
		{
			get
			{
				if (this.Parameters.Contains("RootNodeId"))
				{
					return ((string)(this.Parameters["RootNodeId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RootNodeId"] = value;
			}
		}
		
		public string ResourceRuleList
		{
			get
			{
				if (this.Parameters.Contains("ResourceRuleList"))
				{
					return ((string)(this.Parameters["ResourceRuleList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceRuleList"] = value;
			}
		}
		
		public @__SaveServiceTreedAtaRequest()
		{
			this.RequestName = "_SaveServiceTreeData";
			this.RootNodeId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_SaveServiceTreeData")]
	public partial class @__SaveServiceTreedAtaResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Error = "Error";
			public const string UpdatedRootNode = "UpdatedRootNode";
		}
		
		public const string ActionLogicalName = "_SaveServiceTreeData";
		
		public @__SaveServiceTreedAtaResponse()
		{
		}
		
		public string Error
		{
			get
			{
				if (this.Results.Contains("Error"))
				{
					return ((string)(this.Results["Error"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Error"] = value;
			}
		}
		
		public string UpdatedRootNode
		{
			get
			{
				if (this.Results.Contains("UpdatedRootNode"))
				{
					return ((string)(this.Results["UpdatedRootNode"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UpdatedRootNode"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
