#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_Updatefeatureconfig")]
	public partial class Msdyn_UpdateFeatureConfigRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string FeatureType = "FeatureType";
			public const string Configuration = "Configuration";
		}
		
		public const string ActionLogicalName = "msdyn_Updatefeatureconfig";
		
		public int FeatureType
		{
			get
			{
				if (this.Parameters.Contains("featureType"))
				{
					return ((int)(this.Parameters["featureType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["featureType"] = value;
			}
		}
		
		public string Configuration
		{
			get
			{
				if (this.Parameters.Contains("configuration"))
				{
					return ((string)(this.Parameters["configuration"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["configuration"] = value;
			}
		}
		
		public Msdyn_UpdateFeatureConfigRequest()
		{
			this.RequestName = "msdyn_Updatefeatureconfig";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_Updatefeatureconfig")]
	public partial class Msdyn_UpdateFeatureConfigResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_Updatefeatureconfig";
		
		public Msdyn_UpdateFeatureConfigResponse()
		{
		}
	}
}
#pragma warning restore CS1591
