#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DismissSuggestedActivity")]
	public partial class Msdyn_DismissSuggestedActivityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SuggestedActivityId = "SuggestedActivityId";
			public const string DismissActivity = "DismissActivity";
		}
		
		public const string ActionLogicalName = "msdyn_DismissSuggestedActivity";
		
		public string SuggestedActivityId
		{
			get
			{
				if (this.Parameters.Contains("SuggestedActivityId"))
				{
					return ((string)(this.Parameters["SuggestedActivityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SuggestedActivityId"] = value;
			}
		}
		
		public bool DismissActivity
		{
			get
			{
				if (this.Parameters.Contains("DismissActivity"))
				{
					return ((bool)(this.Parameters["DismissActivity"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["DismissActivity"] = value;
			}
		}
		
		public Msdyn_DismissSuggestedActivityRequest()
		{
			this.RequestName = "msdyn_DismissSuggestedActivity";
			this.SuggestedActivityId = default(string);
			this.DismissActivity = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DismissSuggestedActivity")]
	public partial class Msdyn_DismissSuggestedActivityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_DismissSuggestedActivity";
		
		public Msdyn_DismissSuggestedActivityResponse()
		{
		}
	}
}
#pragma warning restore CS1591
