#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetACIMarsConnectorStatus")]
	public partial class Msdyn_GetAcIMarsConnectorStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_GetACIMarsConnectorStatus";
		
		public Msdyn_GetAcIMarsConnectorStatusRequest()
		{
			this.RequestName = "msdyn_GetACIMarsConnectorStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetACIMarsConnectorStatus")]
	public partial class Msdyn_GetAcIMarsConnectorStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string MarsStatus = "MarsStatus";
		}
		
		public const string ActionLogicalName = "msdyn_GetACIMarsConnectorStatus";
		
		public Msdyn_GetAcIMarsConnectorStatusResponse()
		{
		}
		
		public string MarsStatus
		{
			get
			{
				if (this.Results.Contains("MarsStatus"))
				{
					return ((string)(this.Results["MarsStatus"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["MarsStatus"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
