#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DeleteCalendar")]
	public partial class Msdyn_DeleteCalendarRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CalendarEventInfo = "CalendarEventInfo";
		}
		
		public const string ActionLogicalName = "msdyn_DeleteCalendar";
		
		public string CalendarEventInfo
		{
			get
			{
				if (this.Parameters.Contains("CalendarEventInfo"))
				{
					return ((string)(this.Parameters["CalendarEventInfo"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CalendarEventInfo"] = value;
			}
		}
		
		public Msdyn_DeleteCalendarRequest()
		{
			this.RequestName = "msdyn_DeleteCalendar";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DeleteCalendar")]
	public partial class Msdyn_DeleteCalendarResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string InnerCalendarId = "InnerCalendarId";
		}
		
		public const string ActionLogicalName = "msdyn_DeleteCalendar";
		
		public Msdyn_DeleteCalendarResponse()
		{
		}
		
		public string InnerCalendarId
		{
			get
			{
				if (this.Results.Contains("InnerCalendarId"))
				{
					return ((string)(this.Results["InnerCalendarId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["InnerCalendarId"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
