#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSIFeatureConfiguration")]
	public partial class Msdyn_GetSiFeatureConfigurationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SiParameters = "SiParameters";
		}
		
		public const string ActionLogicalName = "msdyn_GetSIFeatureConfiguration";
		
		public string SiParameters
		{
			get
			{
				if (this.Parameters.Contains("SIParameters"))
				{
					return ((string)(this.Parameters["SIParameters"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SIParameters"] = value;
			}
		}
		
		public Msdyn_GetSiFeatureConfigurationRequest()
		{
			this.RequestName = "msdyn_GetSIFeatureConfiguration";
			this.SiParameters = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSIFeatureConfiguration")]
	public partial class Msdyn_GetSiFeatureConfigurationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string FeatureConfiguration = "FeatureConfiguration";
		}
		
		public const string ActionLogicalName = "msdyn_GetSIFeatureConfiguration";
		
		public Msdyn_GetSiFeatureConfigurationResponse()
		{
		}
		
		public string FeatureConfiguration
		{
			get
			{
				if (this.Results.Contains("FeatureConfiguration"))
				{
					return ((string)(this.Results["FeatureConfiguration"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["FeatureConfiguration"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
