#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecutePrimaryCreatePostActions")]
	public partial class Msdyn_ExecutePrimaryCreatePostActionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SourceEntityReference = "SourceEntityReference";
			public const string PrimaryEntityReference = "PrimaryEntityReference";
			public const string RuleId = "RuleId";
		}
		
		public const string ActionLogicalName = "msdyn_ExecutePrimaryCreatePostActions";
		
		public Microsoft.Xrm.Sdk.EntityReference SourceEntityReference
		{
			get
			{
				if (this.Parameters.Contains("SourceEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["SourceEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["SourceEntityReference"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference PrimaryEntityReference
		{
			get
			{
				if (this.Parameters.Contains("PrimaryEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["PrimaryEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["PrimaryEntityReference"] = value;
			}
		}
		
		public string RuleId
		{
			get
			{
				if (this.Parameters.Contains("RuleId"))
				{
					return ((string)(this.Parameters["RuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RuleId"] = value;
			}
		}
		
		public Msdyn_ExecutePrimaryCreatePostActionsRequest()
		{
			this.RequestName = "msdyn_ExecutePrimaryCreatePostActions";
			this.SourceEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
			this.PrimaryEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
			this.RuleId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecutePrimaryCreatePostActions")]
	public partial class Msdyn_ExecutePrimaryCreatePostActionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "msdyn_ExecutePrimaryCreatePostActions";
		
		public Msdyn_ExecutePrimaryCreatePostActionsResponse()
		{
		}
	}
}
#pragma warning restore CS1591
