#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SIGetFCBStatus")]
	public partial class Msdyn_SiGeTfCBStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string FCBName = "FCBName";
		}
		
		public const string ActionLogicalName = "msdyn_SIGetFCBStatus";
		
		public string FCBName
		{
			get
			{
				if (this.Parameters.Contains("FCBName"))
				{
					return ((string)(this.Parameters["FCBName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FCBName"] = value;
			}
		}
		
		public Msdyn_SiGeTfCBStatusRequest()
		{
			this.RequestName = "msdyn_SIGetFCBStatus";
			this.FCBName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SIGetFCBStatus")]
	public partial class Msdyn_SiGeTfCBStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Status = "Status";
		}
		
		public const string ActionLogicalName = "msdyn_SIGetFCBStatus";
		
		public Msdyn_SiGeTfCBStatusResponse()
		{
		}
		
		public bool Status
		{
			get
			{
				if (this.Results.Contains("Status"))
				{
					return ((bool)(this.Results["Status"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["Status"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
