#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveActivities")]
	public partial class Msdyn_RetrieveActivitiesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string FetchXml = "FetchXml";
			public const string ClientType = "ClientType";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveActivities";
		
		public string FetchXml
		{
			get
			{
				if (this.Parameters.Contains("FetchXml"))
				{
					return ((string)(this.Parameters["FetchXml"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FetchXml"] = value;
			}
		}
		
		public int ClientType
		{
			get
			{
				if (this.Parameters.Contains("ClientType"))
				{
					return ((int)(this.Parameters["ClientType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ClientType"] = value;
			}
		}
		
		public Msdyn_RetrieveActivitiesRequest()
		{
			this.RequestName = "msdyn_RetrieveActivities";
			this.FetchXml = default(string);
			this.ClientType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveActivities")]
	public partial class Msdyn_RetrieveActivitiesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string ActivityList = "ActivityList";
		}
		
		public const string ActionLogicalName = "msdyn_RetrieveActivities";
		
		public Msdyn_RetrieveActivitiesResponse()
		{
		}
		
		public string ActivityList
		{
			get
			{
				if (this.Results.Contains("ActivityList"))
				{
					return ((string)(this.Results["ActivityList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["ActivityList"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
