#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SnoozeEmailInfraActionCard")]
	public partial class Msdyn_SnoozeEmailInfraActionCardRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ActionCardId = "ActionCardId";
			public const string CardType = "CardType";
			public const string MessageId = "MessageId";
		}
		
		public const string ActionLogicalName = "msdyn_SnoozeEmailInfraActionCard";
		
		public string ActionCardId
		{
			get
			{
				if (this.Parameters.Contains("ActionCardId"))
				{
					return ((string)(this.Parameters["ActionCardId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionCardId"] = value;
			}
		}
		
		public int CardType
		{
			get
			{
				if (this.Parameters.Contains("CardType"))
				{
					return ((int)(this.Parameters["CardType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["CardType"] = value;
			}
		}
		
		public string MessageId
		{
			get
			{
				if (this.Parameters.Contains("MessageId"))
				{
					return ((string)(this.Parameters["MessageId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MessageId"] = value;
			}
		}
		
		public Msdyn_SnoozeEmailInfraActionCardRequest()
		{
			this.RequestName = "msdyn_SnoozeEmailInfraActionCard";
			this.ActionCardId = default(string);
			this.CardType = default(int);
			this.MessageId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SnoozeEmailInfraActionCard")]
	public partial class Msdyn_SnoozeEmailInfraActionCardResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Error = "Error";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "msdyn_SnoozeEmailInfraActionCard";
		
		public Msdyn_SnoozeEmailInfraActionCardResponse()
		{
		}
		
		public string Error
		{
			get
			{
				if (this.Results.Contains("Error"))
				{
					return ((string)(this.Results["Error"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Error"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
