#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRITenantEndpoint")]
	public partial class Msdyn_GeTriTenantEndpointRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "msdyn_GetRITenantEndpoint";
		
		public Msdyn_GeTriTenantEndpointRequest()
		{
			this.RequestName = "msdyn_GetRITenantEndpoint";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetRITenantEndpoint")]
	public partial class Msdyn_GeTriTenantEndpointResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string TenantInfo = "TenantInfo";
		}
		
		public const string ActionLogicalName = "msdyn_GetRITenantEndpoint";
		
		public Msdyn_GeTriTenantEndpointResponse()
		{
		}
		
		public string TenantInfo
		{
			get
			{
				if (this.Results.Contains("TenantInfo"))
				{
					return ((string)(this.Results["TenantInfo"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["TenantInfo"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
