#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetServiceBaseUrl")]
	public partial class Msdyn_GetServiceBaseUrlRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string AzureApplicationType = "AzureApplicationType";
		}
		
		public const string ActionLogicalName = "msdyn_GetServiceBaseUrl";
		
		public int AzureApplicationType
		{
			get
			{
				if (this.Parameters.Contains("AzureApplicationType"))
				{
					return ((int)(this.Parameters["AzureApplicationType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["AzureApplicationType"] = value;
			}
		}
		
		public Msdyn_GetServiceBaseUrlRequest()
		{
			this.RequestName = "msdyn_GetServiceBaseUrl";
			this.AzureApplicationType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetServiceBaseUrl")]
	public partial class Msdyn_GetServiceBaseUrlResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string BaseUrl = "BaseUrl";
		}
		
		public const string ActionLogicalName = "msdyn_GetServiceBaseUrl";
		
		public Msdyn_GetServiceBaseUrlResponse()
		{
		}
		
		public string BaseUrl
		{
			get
			{
				if (this.Results.Contains("BaseUrl"))
				{
					return ((string)(this.Results["BaseUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["BaseUrl"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
