#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DataValidationApi")]
	public partial class Msdyn_DataValidationApiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ApiType = "ApiType";
			public const string ApiPayload = "ApiPayload";
		}
		
		public const string ActionLogicalName = "msdyn_DataValidationApi";
		
		public int ApiType
		{
			get
			{
				if (this.Parameters.Contains("ApiType"))
				{
					return ((int)(this.Parameters["ApiType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ApiType"] = value;
			}
		}
		
		public string ApiPayload
		{
			get
			{
				if (this.Parameters.Contains("ApiPayLoad"))
				{
					return ((string)(this.Parameters["ApiPayLoad"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiPayLoad"] = value;
			}
		}
		
		public Msdyn_DataValidationApiRequest()
		{
			this.RequestName = "msdyn_DataValidationApi";
			this.ApiType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DataValidationApi")]
	public partial class Msdyn_DataValidationApiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "msdyn_DataValidationApi";
		
		public Msdyn_DataValidationApiResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
