#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("PvaGetDirectLineEndpoint")]
	public partial class PVaGetDirectLineEndpointRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "PvaGetDirectLineEndpoint";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public PVaGetDirectLineEndpointRequest()
		{
			this.RequestName = "PvaGetDirectLineEndpoint";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("PvaGetDirectLineEndpoint")]
	public partial class PVaGetDirectLineEndpointResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Endpoint = "Endpoint";
		}
		
		public const string ActionLogicalName = "PvaGetDirectLineEndpoint";
		
		public PVaGetDirectLineEndpointResponse()
		{
		}
		
		public string Endpoint
		{
			get
			{
				if (this.Results.Contains("Endpoint"))
				{
					return ((string)(this.Results["Endpoint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Endpoint"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
