#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveCascadeDeleteAsyncJobId")]
	public partial class RetrieveCascadeDeleteAsyncJobIdRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string ParentEntityId = "ParentEntityId";
		}
		
		public const string ActionLogicalName = "RetrieveCascadeDeleteAsyncJobId";
		
		public System.Guid ParentEntityId
		{
			get
			{
				if (this.Parameters.Contains("ParentEntityId"))
				{
					return ((System.Guid)(this.Parameters["ParentEntityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ParentEntityId"] = value;
			}
		}
		
		public RetrieveCascadeDeleteAsyncJobIdRequest()
		{
			this.RequestName = "RetrieveCascadeDeleteAsyncJobId";
			this.ParentEntityId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveCascadeDeleteAsyncJobId")]
	public partial class RetrieveCascadeDeleteAsyncJobIdResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AsyncJobId = "AsyncJobId";
			public const string AsyncJobName = "AsyncJobName";
		}
		
		public const string ActionLogicalName = "RetrieveCascadeDeleteAsyncJobId";
		
		public RetrieveCascadeDeleteAsyncJobIdResponse()
		{
		}
		
		public System.Guid AsyncJobId
		{
			get
			{
				if (this.Results.Contains("AsyncJobId"))
				{
					return ((System.Guid)(this.Results["AsyncJobId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Results["AsyncJobId"] = value;
			}
		}
		
		public string AsyncJobName
		{
			get
			{
				if (this.Results.Contains("AsyncJobName"))
				{
					return ((string)(this.Results["AsyncJobName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["AsyncJobName"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
