#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("rwb_CustomiseRibbon")]
	public partial class RWb_CustomiseRibbonRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Operation = "Operation";
			public const string Data = "Data";
		}
		
		public const string ActionLogicalName = "rwb_CustomiseRibbon";
		
		public string Operation
		{
			get
			{
				if (this.Parameters.Contains("Operation"))
				{
					return ((string)(this.Parameters["Operation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Operation"] = value;
			}
		}
		
		public string Data
		{
			get
			{
				if (this.Parameters.Contains("Data"))
				{
					return ((string)(this.Parameters["Data"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Data"] = value;
			}
		}
		
		public RWb_CustomiseRibbonRequest()
		{
			this.RequestName = "rwb_CustomiseRibbon";
			this.Operation = default(string);
			this.Data = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("rwb_CustomiseRibbon")]
	public partial class RWb_CustomiseRibbonResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "rwb_CustomiseRibbon";
		
		public RWb_CustomiseRibbonResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
