#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("UpsertEnvironmentVariable")]
	public partial class UpsertEnvironmentVariableRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string DataSourceType = "DataSourceType";
			public const string SchemaName = "SchemaName";
			public const string ConnectionId = "ConnectionId";
			public const string Value = "Value";
			public const string DefaultValue = "DefaultValue";
			public const string Type = "Type";
		}
		
		public const string ActionLogicalName = "UpsertEnvironmentVariable";
		
		public string DataSourceType
		{
			get
			{
				if (this.Parameters.Contains("DataSourceType"))
				{
					return ((string)(this.Parameters["DataSourceType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DataSourceType"] = value;
			}
		}
		
		public string SchemaName
		{
			get
			{
				if (this.Parameters.Contains("SchemaName"))
				{
					return ((string)(this.Parameters["SchemaName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SchemaName"] = value;
			}
		}
		
		public string ConnectionId
		{
			get
			{
				if (this.Parameters.Contains("ConnectionId"))
				{
					return ((string)(this.Parameters["ConnectionId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ConnectionId"] = value;
			}
		}
		
		public string Value
		{
			get
			{
				if (this.Parameters.Contains("Value"))
				{
					return ((string)(this.Parameters["Value"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Value"] = value;
			}
		}
		
		public string DefaultValue
		{
			get
			{
				if (this.Parameters.Contains("DefaultValue"))
				{
					return ((string)(this.Parameters["DefaultValue"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DefaultValue"] = value;
			}
		}
		
		public int Type
		{
			get
			{
				if (this.Parameters.Contains("Type"))
				{
					return ((int)(this.Parameters["Type"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Type"] = value;
			}
		}
		
		public UpsertEnvironmentVariableRequest()
		{
			this.RequestName = "UpsertEnvironmentVariable";
			this.SchemaName = default(string);
			this.Type = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("UpsertEnvironmentVariable")]
	public partial class UpsertEnvironmentVariableResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "UpsertEnvironmentVariable";
		
		public UpsertEnvironmentVariableResponse()
		{
		}
	}
}
#pragma warning restore CS1591
