#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_SubmitCounselorInvoice")]
	public partial class Vsd_SubmitCounselorInvoiceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string VendorNumber = "VendorNumber";
			public const string VendorPostalCode = "VendorPostalCode";
			public const string CounselorNumber = "CounselorNumber";
			public const string CounselorLastName = "CounselorLastName";
			public const string ClaimNumber = "ClaimNumber";
			public const string ClaimantFirstName = "ClaimantFirstName";
			public const string ClaimantLastName = "ClaimantLastName";
			public const string InvoiceNumber = "InvoiceNumber";
			public const string InvoicedAte = "InvoicedAte";
			public const string ExemptFromGst = "ExemptFromGst";
			public const string SubmitterFullName = "SubmitterFullName";
			public const string SubmitterEmailAddress = "SubmitterEmailAddress";
			public const string InvoiceLineItems = "InvoiceLineItems";
			public const string DocumentCollection = "DocumentCollection";
		}
		
		public const string ActionLogicalName = "vsd_SubmitCounselorInvoice";
		
		public string VendorNumber
		{
			get
			{
				if (this.Parameters.Contains("VendorNumber"))
				{
					return ((string)(this.Parameters["VendorNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["VendorNumber"] = value;
			}
		}
		
		public string VendorPostalCode
		{
			get
			{
				if (this.Parameters.Contains("VendorPostalCode"))
				{
					return ((string)(this.Parameters["VendorPostalCode"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["VendorPostalCode"] = value;
			}
		}
		
		public string CounselorNumber
		{
			get
			{
				if (this.Parameters.Contains("CounselorNumber"))
				{
					return ((string)(this.Parameters["CounselorNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CounselorNumber"] = value;
			}
		}
		
		public string CounselorLastName
		{
			get
			{
				if (this.Parameters.Contains("CounselorLastName"))
				{
					return ((string)(this.Parameters["CounselorLastName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CounselorLastName"] = value;
			}
		}
		
		public string ClaimNumber
		{
			get
			{
				if (this.Parameters.Contains("ClaimNumber"))
				{
					return ((string)(this.Parameters["ClaimNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ClaimNumber"] = value;
			}
		}
		
		public string ClaimantFirstName
		{
			get
			{
				if (this.Parameters.Contains("ClaimantFirstName"))
				{
					return ((string)(this.Parameters["ClaimantFirstName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ClaimantFirstName"] = value;
			}
		}
		
		public string ClaimantLastName
		{
			get
			{
				if (this.Parameters.Contains("ClaimantLastName"))
				{
					return ((string)(this.Parameters["ClaimantLastName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ClaimantLastName"] = value;
			}
		}
		
		public string InvoiceNumber
		{
			get
			{
				if (this.Parameters.Contains("InvoiceNumber"))
				{
					return ((string)(this.Parameters["InvoiceNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InvoiceNumber"] = value;
			}
		}
		
		public System.DateTime InvoicedAte
		{
			get
			{
				if (this.Parameters.Contains("InvoiceDate"))
				{
					return ((System.DateTime)(this.Parameters["InvoiceDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["InvoiceDate"] = value;
			}
		}
		
		public bool ExemptFromGst
		{
			get
			{
				if (this.Parameters.Contains("ExemptFromGST"))
				{
					return ((bool)(this.Parameters["ExemptFromGST"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExemptFromGST"] = value;
			}
		}
		
		public string SubmitterFullName
		{
			get
			{
				if (this.Parameters.Contains("SubmitterFullName"))
				{
					return ((string)(this.Parameters["SubmitterFullName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SubmitterFullName"] = value;
			}
		}
		
		public string SubmitterEmailAddress
		{
			get
			{
				if (this.Parameters.Contains("SubmitterEmailAddress"))
				{
					return ((string)(this.Parameters["SubmitterEmailAddress"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SubmitterEmailAddress"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection InvoiceLineItems
		{
			get
			{
				if (this.Parameters.Contains("InvoiceLineItems"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["InvoiceLineItems"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["InvoiceLineItems"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection DocumentCollection
		{
			get
			{
				if (this.Parameters.Contains("DocumentCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["DocumentCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["DocumentCollection"] = value;
			}
		}
		
		public Vsd_SubmitCounselorInvoiceRequest()
		{
			this.RequestName = "vsd_SubmitCounselorInvoice";
			this.VendorNumber = default(string);
			this.VendorPostalCode = default(string);
			this.CounselorNumber = default(string);
			this.CounselorLastName = default(string);
			this.ClaimNumber = default(string);
			this.ClaimantFirstName = default(string);
			this.ClaimantLastName = default(string);
			this.InvoiceNumber = default(string);
			this.InvoicedAte = default(System.DateTime);
			this.SubmitterFullName = default(string);
			this.SubmitterEmailAddress = default(string);
			this.InvoiceLineItems = default(Microsoft.Xrm.Sdk.EntityCollection);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_SubmitCounselorInvoice")]
	public partial class Vsd_SubmitCounselorInvoiceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsSuccess = "IsSuccess";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "vsd_SubmitCounselorInvoice";
		
		public Vsd_SubmitCounselorInvoiceResponse()
		{
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
