#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_AgeCalculator")]
	public partial class Vsd_AgeCalculatorRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Birthdate = "Birthdate";
			public const string EndDate = "EndDate";
		}
		
		public const string ActionLogicalName = "vsd_AgeCalculator";
		
		public System.DateTime Birthdate
		{
			get
			{
				if (this.Parameters.Contains("BirthDate"))
				{
					return ((System.DateTime)(this.Parameters["BirthDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["BirthDate"] = value;
			}
		}
		
		public System.DateTime EndDate
		{
			get
			{
				if (this.Parameters.Contains("EndDate"))
				{
					return ((System.DateTime)(this.Parameters["EndDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["EndDate"] = value;
			}
		}
		
		public Vsd_AgeCalculatorRequest()
		{
			this.RequestName = "vsd_AgeCalculator";
			this.Birthdate = default(System.DateTime);
			this.EndDate = default(System.DateTime);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_AgeCalculator")]
	public partial class Vsd_AgeCalculatorResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string Age = "Age";
			public const string IsSuccess = "IsSuccess";
			public const string UserMessage = "UserMessage";
		}
		
		public const string ActionLogicalName = "vsd_AgeCalculator";
		
		public Vsd_AgeCalculatorResponse()
		{
		}
		
		public int Age
		{
			get
			{
				if (this.Results.Contains("Age"))
				{
					return ((int)(this.Results["Age"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Results["Age"] = value;
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string UserMessage
		{
			get
			{
				if (this.Results.Contains("UserMessage"))
				{
					return ((string)(this.Results["UserMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UserMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
