#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_HasActiveChildAction")]
	public partial class Vsd_HasActiveChildActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntitySchemaName = "EntitySchemaName";
			public const string EntityPrimaryKeyName = "EntityPrimaryKeyName";
			public const string EntityPrimaryKeyValue = "EntityPrimaryKeyValue";
		}
		
		public const string ActionLogicalName = "vsd_HasActiveChildAction";
		
		public string EntitySchemaName
		{
			get
			{
				if (this.Parameters.Contains("EntitySchemaName"))
				{
					return ((string)(this.Parameters["EntitySchemaName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntitySchemaName"] = value;
			}
		}
		
		public string EntityPrimaryKeyName
		{
			get
			{
				if (this.Parameters.Contains("EntityPrimaryKeyName"))
				{
					return ((string)(this.Parameters["EntityPrimaryKeyName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityPrimaryKeyName"] = value;
			}
		}
		
		public string EntityPrimaryKeyValue
		{
			get
			{
				if (this.Parameters.Contains("EntityPrimaryKeyValue"))
				{
					return ((string)(this.Parameters["EntityPrimaryKeyValue"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityPrimaryKeyValue"] = value;
			}
		}
		
		public Vsd_HasActiveChildActionRequest()
		{
			this.RequestName = "vsd_HasActiveChildAction";
			this.EntitySchemaName = default(string);
			this.EntityPrimaryKeyName = default(string);
			this.EntityPrimaryKeyValue = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_HasActiveChildAction")]
	public partial class Vsd_HasActiveChildActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string HasActiveChild = "HasActiveChild";
			public const string UserMessage = "UserMessage";
		}
		
		public const string ActionLogicalName = "vsd_HasActiveChildAction";
		
		public Vsd_HasActiveChildActionResponse()
		{
		}
		
		public bool HasActiveChild
		{
			get
			{
				if (this.Results.Contains("HasActiveChild"))
				{
					return ((bool)(this.Results["HasActiveChild"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["HasActiveChild"] = value;
			}
		}
		
		public string UserMessage
		{
			get
			{
				if (this.Results.Contains("UserMessage"))
				{
					return ((string)(this.Results["UserMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UserMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
