#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_ResetCaseAutonumbering")]
	public partial class Vsd_ResetCaseAutoNumberingRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public const string ActionLogicalName = "vsd_ResetCaseAutonumbering";
		
		public Vsd_ResetCaseAutoNumberingRequest()
		{
			this.RequestName = "vsd_ResetCaseAutonumbering";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_ResetCaseAutonumbering")]
	public partial class Vsd_ResetCaseAutoNumberingResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public const string ActionLogicalName = "vsd_ResetCaseAutonumbering";
		
		public Vsd_ResetCaseAutoNumberingResponse()
		{
		}
	}
}
#pragma warning restore CS1591
