#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_GetCaseTitleAction")]
	public partial class Vsd_GetCaseTitleActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CurrentCaseTitle = "CurrentCaseTitle";
			public const string TicketNumber = "TicketNumber";
			public const string IsRegistered = "IsRegistered";
			public const string ClientFirstName = "ClientFirstName";
			public const string ClientLastName = "ClientLastName";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "vsd_GetCaseTitleAction";
		
		public string CurrentCaseTitle
		{
			get
			{
				if (this.Parameters.Contains("CurrentCaseTitle"))
				{
					return ((string)(this.Parameters["CurrentCaseTitle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CurrentCaseTitle"] = value;
			}
		}
		
		public string TicketNumber
		{
			get
			{
				if (this.Parameters.Contains("TicketNumber"))
				{
					return ((string)(this.Parameters["TicketNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TicketNumber"] = value;
			}
		}
		
		public bool IsRegistered
		{
			get
			{
				if (this.Parameters.Contains("IsRegistered"))
				{
					return ((bool)(this.Parameters["IsRegistered"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsRegistered"] = value;
			}
		}
		
		public string ClientFirstName
		{
			get
			{
				if (this.Parameters.Contains("ClientFirstName"))
				{
					return ((string)(this.Parameters["ClientFirstName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ClientFirstName"] = value;
			}
		}
		
		public string ClientLastName
		{
			get
			{
				if (this.Parameters.Contains("ClientLastName"))
				{
					return ((string)(this.Parameters["ClientLastName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ClientLastName"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Vsd_GetCaseTitleActionRequest()
		{
			this.RequestName = "vsd_GetCaseTitleAction";
			this.TicketNumber = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_GetCaseTitleAction")]
	public partial class Vsd_GetCaseTitleActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string NewCaseTitle = "NewCaseTitle";
		}
		
		public const string ActionLogicalName = "vsd_GetCaseTitleAction";
		
		public Vsd_GetCaseTitleActionResponse()
		{
		}
		
		public string NewCaseTitle
		{
			get
			{
				if (this.Results.Contains("NewCaseTitle"))
				{
					return ((string)(this.Results["NewCaseTitle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["NewCaseTitle"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
