#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_CORNETOffenderSearch")]
	public partial class Vsd_CornetOffenderSearchRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string SearchType = "SearchType";
			public const string Surname = "Surname";
			public const string Given1 = "Given1";
			public const string Given2 = "Given2";
			public const string BirthYear = "BirthYear";
			public const string BirthYeArrange = "BirthYeArrange";
			public const string Gender = "Gender";
			public const string IdentifierType = "IdentifierType";
			public const string IdentifierText = "IdentifierText";
			public const string Username = "Username";
			public const string FullName = "FullName";
			public const string Client = "Client";
		}
		
		public const string ActionLogicalName = "vsd_CORNETOffenderSearch";
		
		public string SearchType
		{
			get
			{
				if (this.Parameters.Contains("SearchType"))
				{
					return ((string)(this.Parameters["SearchType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SearchType"] = value;
			}
		}
		
		public string Surname
		{
			get
			{
				if (this.Parameters.Contains("Surname"))
				{
					return ((string)(this.Parameters["Surname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Surname"] = value;
			}
		}
		
		public string Given1
		{
			get
			{
				if (this.Parameters.Contains("Given1"))
				{
					return ((string)(this.Parameters["Given1"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Given1"] = value;
			}
		}
		
		public string Given2
		{
			get
			{
				if (this.Parameters.Contains("Given2"))
				{
					return ((string)(this.Parameters["Given2"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Given2"] = value;
			}
		}
		
		public string BirthYear
		{
			get
			{
				if (this.Parameters.Contains("BirthYear"))
				{
					return ((string)(this.Parameters["BirthYear"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BirthYear"] = value;
			}
		}
		
		public string BirthYeArrange
		{
			get
			{
				if (this.Parameters.Contains("BirthYearRange"))
				{
					return ((string)(this.Parameters["BirthYearRange"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BirthYearRange"] = value;
			}
		}
		
		public string Gender
		{
			get
			{
				if (this.Parameters.Contains("Gender"))
				{
					return ((string)(this.Parameters["Gender"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Gender"] = value;
			}
		}
		
		public string IdentifierType
		{
			get
			{
				if (this.Parameters.Contains("IdentifierType"))
				{
					return ((string)(this.Parameters["IdentifierType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IdentifierType"] = value;
			}
		}
		
		public string IdentifierText
		{
			get
			{
				if (this.Parameters.Contains("IdentifierText"))
				{
					return ((string)(this.Parameters["IdentifierText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IdentifierText"] = value;
			}
		}
		
		public string Username
		{
			get
			{
				if (this.Parameters.Contains("UserName"))
				{
					return ((string)(this.Parameters["UserName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UserName"] = value;
			}
		}
		
		public string FullName
		{
			get
			{
				if (this.Parameters.Contains("FullName"))
				{
					return ((string)(this.Parameters["FullName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FullName"] = value;
			}
		}
		
		public string Client
		{
			get
			{
				if (this.Parameters.Contains("Client"))
				{
					return ((string)(this.Parameters["Client"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Client"] = value;
			}
		}
		
		public Vsd_CornetOffenderSearchRequest()
		{
			this.RequestName = "vsd_CORNETOffenderSearch";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_CORNETOffenderSearch")]
	public partial class Vsd_CornetOffenderSearchResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsSuccess = "IsSuccess";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "vsd_CORNETOffenderSearch";
		
		public Vsd_CornetOffenderSearchResponse()
		{
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
