#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_GetDocumentType")]
	public partial class Vsd_GetDocumentTypeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Code = "Code";
			public const string Name = "Name";
		}
		
		public const string ActionLogicalName = "vsd_GetDocumentType";
		
		public string Code
		{
			get
			{
				if (this.Parameters.Contains("Code"))
				{
					return ((string)(this.Parameters["Code"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Code"] = value;
			}
		}
		
		public string Name
		{
			get
			{
				if (this.Parameters.Contains("Name"))
				{
					return ((string)(this.Parameters["Name"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Name"] = value;
			}
		}
		
		public Vsd_GetDocumentTypeRequest()
		{
			this.RequestName = "vsd_GetDocumentType";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_GetDocumentType")]
	public partial class Vsd_GetDocumentTypeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string DocumentType = "DocumentType";
			public const string IsSuccess = "IsSuccess";
		}
		
		public const string ActionLogicalName = "vsd_GetDocumentType";
		
		public Vsd_GetDocumentTypeResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference DocumentType
		{
			get
			{
				if (this.Results.Contains("DocumentType"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["DocumentType"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Results["DocumentType"] = value;
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
