#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_CanCaseBeClosedAction")]
	public partial class Vsd_CanCaseBeClosedActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CaseNumber = "CaseNumber";
		}
		
		public const string ActionLogicalName = "vsd_CanCaseBeClosedAction";
		
		public string CaseNumber
		{
			get
			{
				if (this.Parameters.Contains("CaseNumber"))
				{
					return ((string)(this.Parameters["CaseNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CaseNumber"] = value;
			}
		}
		
		public Vsd_CanCaseBeClosedActionRequest()
		{
			this.RequestName = "vsd_CanCaseBeClosedAction";
			this.CaseNumber = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_CanCaseBeClosedAction")]
	public partial class Vsd_CanCaseBeClosedActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CanBeClosed = "CanBeClosed";
			public const string UserMessage = "UserMessage";
		}
		
		public const string ActionLogicalName = "vsd_CanCaseBeClosedAction";
		
		public Vsd_CanCaseBeClosedActionResponse()
		{
		}
		
		public bool CanBeClosed
		{
			get
			{
				if (this.Results.Contains("CanBeClosed"))
				{
					return ((bool)(this.Results["CanBeClosed"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["CanBeClosed"] = value;
			}
		}
		
		public string UserMessage
		{
			get
			{
				if (this.Results.Contains("UserMessage"))
				{
					return ((string)(this.Results["UserMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UserMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
