#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_IsCaseInactive")]
	public partial class Vsd_IsCaseInactiveRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "vsd_IsCaseInactive";
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Vsd_IsCaseInactiveRequest()
		{
			this.RequestName = "vsd_IsCaseInactive";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_IsCaseInactive")]
	public partial class Vsd_IsCaseInactiveResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsInactive = "IsInactive";
		}
		
		public const string ActionLogicalName = "vsd_IsCaseInactive";
		
		public Vsd_IsCaseInactiveResponse()
		{
		}
		
		public bool IsInactive
		{
			get
			{
				if (this.Results.Contains("IsInactive"))
				{
					return ((bool)(this.Results["IsInactive"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsInactive"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
