#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_ValidateClaimLastCourtDate")]
	public partial class Vsd_ValidateClaimLastCourtDateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CaseId = "CaseId";
			public const string Target = "Target";
		}
		
		public const string ActionLogicalName = "vsd_ValidateClaimLastCourtDate";
		
		public Microsoft.Xrm.Sdk.EntityReference CaseId
		{
			get
			{
				if (this.Parameters.Contains("CaseId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CaseId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CaseId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Vsd_ValidateClaimLastCourtDateRequest()
		{
			this.RequestName = "vsd_ValidateClaimLastCourtDate";
			this.CaseId = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_ValidateClaimLastCourtDate")]
	public partial class Vsd_ValidateClaimLastCourtDateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsLessThan18Months = "IsLessThan18Months";
			public const string UserMessage = "UserMessage";
		}
		
		public const string ActionLogicalName = "vsd_ValidateClaimLastCourtDate";
		
		public Vsd_ValidateClaimLastCourtDateResponse()
		{
		}
		
		public bool IsLessThan18Months
		{
			get
			{
				if (this.Results.Contains("IsLessThan18Months"))
				{
					return ((bool)(this.Results["IsLessThan18Months"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsLessThan18Months"] = value;
			}
		}
		
		public string UserMessage
		{
			get
			{
				if (this.Results.Contains("UserMessage"))
				{
					return ((string)(this.Results["UserMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UserMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
