#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_IsMinor")]
	public partial class Vsd_IsMinorRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string Birthdate = "Birthdate";
		}
		
		public const string ActionLogicalName = "vsd_IsMinor";
		
		public System.DateTime Birthdate
		{
			get
			{
				if (this.Parameters.Contains("BirthDate"))
				{
					return ((System.DateTime)(this.Parameters["BirthDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["BirthDate"] = value;
			}
		}
		
		public Vsd_IsMinorRequest()
		{
			this.RequestName = "vsd_IsMinor";
			this.Birthdate = default(System.DateTime);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_IsMinor")]
	public partial class Vsd_IsMinorResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string AdultAgeDate = "AdultAgeDate";
			public const string IsMinor = "IsMinor";
			public const string UserMessage = "UserMessage";
		}
		
		public const string ActionLogicalName = "vsd_IsMinor";
		
		public Vsd_IsMinorResponse()
		{
		}
		
		public System.DateTime AdultAgeDate
		{
			get
			{
				if (this.Results.Contains("AdultAgeDate"))
				{
					return ((System.DateTime)(this.Results["AdultAgeDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Results["AdultAgeDate"] = value;
			}
		}
		
		public bool IsMinor
		{
			get
			{
				if (this.Results.Contains("IsMinor"))
				{
					return ((bool)(this.Results["IsMinor"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsMinor"] = value;
			}
		}
		
		public string UserMessage
		{
			get
			{
				if (this.Results.Contains("UserMessage"))
				{
					return ((string)(this.Results["UserMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["UserMessage"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
