using Resources;

public class PaymentScheduleTests(IMediator mediator, IMessageRequests messageRequests, IEntitlementRepository entitlementRepository, ILoggerFactory loggingFactory)
{
    private readonly ILogger _logger = loggingFactory.CreateLogger<PaymentScheduleTests>();

    // NOTE not a practical integration test, used to speed up the development of PaymentController.SchedulePayment service
    [Fact]
    public async Task Schedule_Payment()
    {
        var cadCurrencyCommand = new GetCurrencyLookupCommand();
        var cadCurrency = await mediator.Send(cadCurrencyCommand);

        var teamQuery = new SingleTeamQuery();
        teamQuery.Name = "CVAP Administrative Team";
        teamQuery.TeamType = TeamType.Owner;
        var adminTeam = await mediator.Send(teamQuery);
        if (adminTeam == null)
        {
            throw new Exception("CVAP Admin Team not found.");
        }

        var incomeSupportParamterQuery = new SingleIncomeSupportParameterQuery();
        incomeSupportParamterQuery.Type = IncomeSupportParameterType.MinimumWage;
        incomeSupportParamterQuery.BeforeEffectiveDate = DateTime.Today;
        incomeSupportParamterQuery.StateCode = StateCode.Active;
        incomeSupportParamterQuery.StatusCode = IncomeSupportParameterStatusCode.Active;
        incomeSupportParamterQuery.Validated = YesNo.Yes;
        var minimumWage = await mediator.Send(incomeSupportParamterQuery);

        var paymentScheduleQuery = new PaymentScheduleEntitlementQuery();
        paymentScheduleQuery.PaymentScheduleQuery = new PaymentScheduleQuery();
        paymentScheduleQuery.PaymentScheduleQuery.StateCode = StateCode.Active;
        paymentScheduleQuery.PaymentScheduleQuery.BeforeStartDate = DateTime.Now;
        paymentScheduleQuery.PaymentScheduleQuery.BeforeNextRunDate = DateTime.Now;
        paymentScheduleQuery.PaymentScheduleQuery.NotNullCaseId = true;
        paymentScheduleQuery.PaymentScheduleQuery.NotNullPayeeId = true;
        paymentScheduleQuery.EntitlementQuery = new EntitlementQuery();
        paymentScheduleQuery.EntitlementQuery.StatusCode = EntitlementStatusCode.Approved;
        paymentScheduleQuery.EntitlementQuery.PaymentScheduleStatus = PaymentScheduleStatus.Active;
        paymentScheduleQuery.EntitlementQuery.IsRecurring = true;

        var paymentScheduleEntitlements = await mediator.Send(paymentScheduleQuery);
        foreach (var paymentScheduleEntitlement in paymentScheduleEntitlements)
        {
            var paymentSchedule = paymentScheduleEntitlement.PaymentSchedule;
            var entitlement = paymentScheduleEntitlement.Entitlement;

            if (paymentSchedule.NextRunDate == null)
                continue;
            var oldRunTime = paymentSchedule.NextRunDate.Value.ToLocalTime(); //OnOrBefore operator doesn't look at time and only looks at date.
            if (oldRunTime > DateTime.Now)
                continue;

            if (entitlement.SetCap == null)
                continue;

            if (paymentSchedule.EndDate != null)
            {
                var endDate = paymentSchedule.EndDate.Value.ToLocalTime();
                if (endDate < DateTime.Now)
                {
                    // update entitlement to have payment schedule status "Inactive" (Cancelled)
                    _logger.LogInformation(string.Format("Updating Payment Schedule Status to Inactive for '{0}'..", entitlement.Id));
                    entitlementRepository.UpdatePaymentScheduleStatus(entitlement.Id, PaymentScheduleStatus.Cancelled);

                    messageRequests.SetState(Vsd_PaymentSchedule.EntityLogicalName, paymentScheduleEntitlement.PaymentSchedule.Id, 1, 2);
                }
            }

            #region Create Invoice & Payment

            var invoice = new Invoice();
            _logger.LogInformation("Entering into Invoice creation");
            invoice.Id = Guid.NewGuid();
            invoice.Origin = Origin.AutoGenerated;
            invoice.CvapInvoiceType = InvoiceType.OtherPayments;
            invoice.InvoiceDate = DateTime.Now;
            invoice.PayeeId = paymentSchedule.PayeeId;
            invoice.CaseId = paymentSchedule.CaseId;
            invoice.OwnerId = adminTeam.Id;
            invoice.EntitlementId = paymentSchedule.EntitlementId;
            invoice.CvapAuthorizationStatus = CvapAuthorizationStatus.ApprovedByQr;
            invoice.AuthorizationDate = DateTime.Now;
            invoice.ProgramUnit = ProgramUnit.Cvap;
            invoice.CurrencyId = cadCurrency.Id;
            invoice.CvapPaymentType = CvapPaymentType.PostAdjudication; // 100000001
            invoice.StatusCode = InvoiceStatusCode.Submitted;
            invoice.MethodOfPayment = MethodOfPayment.Cheque;
            invoice.CvapNumberOfLineItems = CvapNumberOfLineItems._1; //100000000 //1
            invoice.CvapStobId = Constant.CvapStobId; //7902 - Entitlements
            invoice.ProcessId = Guid.Empty;
            invoice.ProvinceStateId = Constant.ProvinceBc;
            invoice.PaymentScheduleId = paymentSchedule.Id;
            if (entitlement.TaxExemptFlag ?? false)
                invoice.TaxExemption = TaxExemption.NoTax;
            else
                invoice.TaxExemption = TaxExemption.GstOnly;
            var insertInvoiceCommand = new InsertCommand<Invoice>(invoice);
            await mediator.Send(insertInvoiceCommand);

            var getPaymentTotalCommand = new GetPaymentTotalCommand
            {
                PaymentSchedule = paymentSchedule,
                Entitlement = entitlement
            };
            getPaymentTotalCommand.MinimumWage = minimumWage.Value;
            var paymentAmounts = await mediator.Send(getPaymentTotalCommand);

            var payment = new Payment();
            payment.Date = DateTime.Now;
            if (entitlement.TaxExemptFlag ?? false)
            {
                payment.SubTotal = paymentAmounts.Amount;
                payment.Total = payment.SubTotal;
            }
            else
            {
                var bcProvinceQuery = new FindProvinceQuery();
                bcProvinceQuery.Id = Constant.ProvinceBc;
                var bcProvince = await mediator.Send(bcProvinceQuery);
                ArgumentNullException.ThrowIfNull(bcProvince.TaxRate);

                payment.SubTotal = paymentAmounts.Amount;
                payment.Gst = (decimal)payment.SubTotal * (decimal)bcProvince.TaxRate;
                payment.Total = (decimal)payment.SubTotal + payment.Gst;
            }

            payment.GlDate = DateTime.Now;
            payment.Terms = PaymentTerms.Immediate;
            payment.CaseId = paymentSchedule.CaseId;
            payment.EntitlementId = paymentSchedule.EntitlementId;
            //paymentEntity["ownerid"] = adminTeam;
            payment.Payee = invoice.PayeeId;
            payment.TransactionCurrencyId = cadCurrency.Id;
            payment.EftAdvice = EftAdvice.Mail;

            //VS-5752
            payment.RemittanceMessage1 = paymentSchedule.CaseName;// ((EntityReference)paymentScheduleEntity["vsd_caseid"]).Name;
            //payment.RemittanceMessage2 = ((EntityReference)invoiceEntity["vsd_entitlementid"]).Name;
            //payment.RemittanceMessage3 = "Crime Victim Assistance Program";

            ////****Add Line Item
            //Entity lineEntity = new Entity("vsd_invoiceid");
            ////lineEntity["vsd_name"] = ((EntityReference)paymentScheduleEntity["vsd_entitlementid"]).Name;
            //lineEntity["vsd_caseid"] = invoiceEntity["vsd_caseid"];
            //lineEntity["vsd_entitlementid"] = invoiceEntity["vsd_entitlementid"];
            //lineEntity["vsd_invoiceid"] = invoiceEntity.ToEntityReference();
            ////lineEntity["ownerid"] = adminTeam;
            //lineEntity["vsd_amountsimple"] = payment["vsd_paymentsubtotal"];
            //lineEntity["vsd_invoicetype"] = new OptionSetValue(100000001); //Other Payments
            //lineEntity["vsd_lineitemapproved"] = new OptionSetValue(100000001); //Yes
            //lineEntity["vsd_provincestateid"] = new EntityReference("vsd_province", new Guid("FDE4DBCA-989A-E811-8155-480FCFF4F6A1")); //BC
            //lineEntity["vsd_taxexemption"] = (OptionSetValue)invoiceEntity["vsd_taxexemption"];
            //lineEntity["vsd_programunit"] = new OptionSetValue(100000000); //CVAP
            //lineEntity["transactioncurrencyid"] = currencyLookup;

            //EntityCollection lineCollection = new EntityCollection();
            //lineCollection.EntityName = "vsd_invoicelinedetail";
            //lineCollection.Entities.Add(lineEntity);
            //Relationship lineRelationship = new Relationship("vsd_vsd_invoice_vsd_invoicelinedetail");
            //invoiceEntity.RelatedEntities.Add(lineRelationship, lineCollection);

            //EntityCollection invoiceCollection = new EntityCollection();
            //invoiceCollection.EntityName = "vsd_invoice";
            //invoiceCollection.Entities.Add(invoiceEntity);
            //Relationship invoiceRelationship = new Relationship("vsd_vsd_payment_vsd_invoice");
            //payment.RelatedEntities.Add(invoiceRelationship, invoiceCollection);

            //payment.Id = OrgService.Create(payment);

            //Entity updateInvoice = new Entity("vsd_invoice");
            //updateInvoice.Id = invoiceEntity.Id;
            //updateInvoice["vsd_paymentid"] = payment.ToEntityReference();
            //OrgService.Update(updateInvoice);

            #endregion

            //#region Update Next Run Time
            ////****Check for weekdays
            //var nextRunDate = GetNextRuntime(paymentScheduleEntity);

            //bool deactivateNextRun = false;
            //if (paymentScheduleEntity.Contains("vsd_enddate") && paymentScheduleEntity["vsd_enddate"] != null)
            //{
            //    var endDate = ((DateTime)paymentScheduleEntity["vsd_enddate"]).ToLocalTime();
            //    if (endDate <= nextRunDate)
            //    {
            //        Log.AppendLine("Deactivating payment schedule due to end date is earlier than next run date");
            //        deactivateNextRun = true;   //VS-6245: if enddate is earlier or equals to next run date then deactivate the schedule 
            //                                    //  continue;   //removed due to VS-6245
            //    }
            //}

            //Log.AppendLine("Updating the Next Run Date and total income support amount..");
            //Entity updatePaymentSchedule = new Entity("vsd_paymentschedule");
            //updatePaymentSchedule.Id = paymentScheduleEntity.Id;
            //if (!paymentScheduleEntity.Contains("vsd_firstrundate"))
            //    updatePaymentSchedule["vsd_firstrundate"] = paymentScheduleEntity["vsd_nextrundate"];
            //updatePaymentSchedule["vsd_totalamountofincomesupport"] = paymentAmounts.Item1;

            //if (deactivateNextRun == true)    //VS-6245
            //{
            //    updatePaymentSchedule["statecode"] = new OptionSetValue(1); //Inactive
            //    updatePaymentSchedule["statuscode"] = new OptionSetValue(2);
            //}
            //else
            //{
            //    updatePaymentSchedule["vsd_nextrundate"] = nextRunDate;
            //}

            //updatePaymentSchedule["vsd_actualvalue"] = paymentAmounts.Item2;

            ////Added new logic//VS-4531.
            //if (paymentScheduleEntity.Contains("vsd_overpaymentemi") && paymentScheduleEntity["vsd_overpaymentemi"] != null && paymentScheduleEntity.Contains("vsd_overpaymentamount") && paymentScheduleEntity["vsd_overpaymentamount"] != null)
            //{
            //    var overPayment = ((Money)paymentScheduleEntity["vsd_overpaymentamount"]).Value;
            //    var emi = ((Money)paymentScheduleEntity["vsd_overpaymentemi"]).Value;

            //    if ((overPayment - emi) >= 0)
            //    {
            //        updatePaymentSchedule["vsd_remainingpaymentamount"] = overPayment - emi;
            //    }
            //    else if ((overPayment - emi) < 0)
            //    {
            //        updatePaymentSchedule["vsd_remainingpaymentamount"] = 0;
            //    }
            //}
            //OrgService.Update(updatePaymentSchedule);
        }
    }
}
